#!/bin/sh

make clean

rm -rvf include/gtest include/gmock

for i in Makefile CMakeFiles CMakeCache.txt cmake_install.cmake CTestTestfile.cmake Testing; do
    find . -name "$i" -exec rm  -rvf {} \;
done
