#!/bin/sh

rm -rf include/gtest include/gmock

for i in Makefile CMakeFiles CMakeCache.txt cmake_install.cmake; do
    find . -name "$i" -exec rm  -rf {} \;
done

rm -f _simplex _testmatrix src/lib*.a
